// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Node_fs = require("bs-platform/lib/js/node_fs.js");
var Readline = require("readline");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var $$Buffer = /* module */[];

var Stream = /* module */[];

var Fs = /* module */[/* Watch */Node_fs.Watch];

var Zlib = /* module */[];

function createInterface(input, output, param) {
  var tmp = {
    input: input
  };
  if (output !== undefined) {
    tmp.output = Caml_option.valFromOption(output);
  }
  return Readline.createInterface(tmp);
}

var Readline$1 = /* module */[/* createInterface */createInterface];

exports.$$Buffer = $$Buffer;
exports.Stream = Stream;
exports.Fs = Fs;
exports.Zlib = Zlib;
exports.Readline = Readline$1;
/* readline Not a pure module */
