// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function logList(lst) {
  console.log(Belt_Array.map(Belt_List.toArray(lst), Belt_List.toArray));
  return /* () */0;
}

var Utils = /* module */[/* logList */logList];

function sleep(ms) {
  return new Promise((function (resolve, _reject) {
                setTimeout((function (param) {
                        return resolve(/* () */0);
                      }), ms);
                return /* () */0;
              }));
}

function sleepAndLog(ms, message) {
  return sleep(ms).then((function (param) {
                return Promise.resolve((console.log(message), /* () */0));
              }));
}

function reduce(lst, acc, reducer) {
  if (lst) {
    var rest = lst[1];
    return Curry._2(reducer, acc, lst[0]).then((function (newAcc) {
                  return reduce(rest, newAcc, reducer);
                }));
  } else {
    return Promise.resolve(acc);
  }
}

var JsPromise = /* module */[
  /* sleep */sleep,
  /* sleepAndLog */sleepAndLog,
  /* reduce */reduce
];

exports.Utils = Utils;
exports.JsPromise = JsPromise;
/* No side effect */
