// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var BetterSqlite3 = require("better-sqlite3");

var Statement = /* module */[];

var Database = /* module */[];

function makeDatabase(path, memory, readonly, fileMustExist, timeout, param) {
  var tmp = { };
  if (memory !== undefined) {
    tmp.memory = Caml_option.valFromOption(memory);
  }
  if (readonly !== undefined) {
    tmp.readonly = Caml_option.valFromOption(readonly);
  }
  if (fileMustExist !== undefined) {
    tmp.fileMustExist = Caml_option.valFromOption(fileMustExist);
  }
  if (timeout !== undefined) {
    tmp.timeout = Caml_option.valFromOption(timeout);
  }
  return new BetterSqlite3(path, tmp);
}

exports.Statement = Statement;
exports.Database = Database;
exports.makeDatabase = makeDatabase;
/* better-sqlite3 Not a pure module */
