// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var Fs = /* module */[];

var $$Buffer = /* module */[];

exports.Fs = Fs;
exports.$$Buffer = $$Buffer;
/* No side effect */
