// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Node_fs = require("bs-platform/lib/js/node_fs.js");

var Fs = /* module */[/* Watch */Node_fs.Watch];

var $$Buffer = /* module */[];

var Zlib = /* module */[];

exports.Fs = Fs;
exports.$$Buffer = $$Buffer;
exports.Zlib = Zlib;
/* No side effect */
