// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Axios = require("axios");

var cfg = {
  responseType: "arraybuffer"
};

Axios.get("https://picsum.photos/100/100/?random", cfg).then((function (res) {
        var buffer = res.data;
        console.log("Size in bytes: " + String(buffer.length));
        Fs.writeFileSync("random.jpg", buffer);
        console.log("Wrote file to random.jpg");
        return Promise.resolve(/* () */0);
      }));

exports.cfg = cfg;
/*  Not a pure module */
