// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

((require('isomorphic-fetch')));

var Response = /* module */[];

var Fs$1 = /* module */[];

var $$Buffer = /* module */[];

fetch("https://picsum.photos/100/100/?random").then((function (prim) {
          return prim.buffer();
        })).then((function (buffer) {
        console.log("Size in bytes: " + String(buffer.length));
        Fs.writeFileSync("random.jpg", buffer);
        console.log("Wrote file to random.jpg");
        return Promise.resolve(/* () */0);
      }));

exports.Response = Response;
exports.Fs = Fs$1;
exports.$$Buffer = $$Buffer;
/*  Not a pure module */
