// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Zlib = require("zlib");
var Axios = require("axios");
var Stream = require("stream");
var Interop = require("./helpers/Interop.bs.js");

var url = "https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz";

var filename = "cedict.txt.gz";

if (Fs.existsSync(filename)) {
  console.log("Reading cedict.txt.gz");
  var readStream = Fs.createReadStream(filename);
  var gunzip = Zlib.createGunzip();
  Stream.pipeline(readStream, gunzip);
  var $$interface = Interop.Readline[/* createInterface */0](gunzip, undefined, /* () */0);
  $$interface.on("line", (function (line) {
          console.log(line);
          return /* () */0;
        }));
} else {
  Axios.get(url, {
          responseType: "arraybuffer"
        }).then((function (res) {
          var buffer = res.data;
          Fs.writeFileSync(filename, buffer);
          return Promise.resolve(/* () */0);
        }));
  console.log("Downloaded cedict.txt.gz");
}

exports.url = url;
exports.filename = filename;
/*  Not a pure module */
