// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Prelude = require("./helpers/Prelude.bs.js");

console.log("I'm sleepy...");

Prelude.JsPromise[/* sleepAndLog */1](1000, "woke up after 1000").then((function (param) {
            return Prelude.JsPromise[/* sleepAndLog */1](1200, "woke up after 1200");
          })).then((function (param) {
          return Prelude.JsPromise[/* sleepAndLog */1](1500, "woke up after 1500");
        })).then((function (param) {
        return Promise.resolve((console.log("done!"), /* () */0));
      }));

var P = 0;

exports.P = P;
/*  Not a pure module */
