// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Prelude = require("./helpers/Prelude.bs.js");

console.log("I'm sleepy...");

Prelude.JsPromise[/* sleep */0](1000).then((function (param) {
          console.log("woke up after 1000");
          return Prelude.JsPromise[/* sleep */0](1200);
        })).then((function (param) {
        return Promise.resolve((console.log("woke up after 1200"), /* () */0));
      }));

var P = 0;

exports.P = P;
/*  Not a pure module */
