// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Prelude = require("./helpers/Prelude.bs.js");

function simple(param) {
  console.log("I'm sleepy...");
  return Prelude.JsPromise[/* sleepAndLog */1](1000, "woke up after 1000").then((function (param) {
                    return Prelude.JsPromise[/* sleepAndLog */1](1200, "woke up after 1200");
                  })).then((function (param) {
                  return Prelude.JsPromise[/* sleepAndLog */1](1500, "woke up after 1500");
                })).then((function (param) {
                return Promise.resolve((console.log("simple is done!"), /* () */0));
              }));
}

function reduce(param) {
  return Prelude.JsPromise[/* reduce */2](/* :: */[
                100,
                /* :: */[
                  1000,
                  /* :: */[
                    1200,
                    /* :: */[
                      1500,
                      /* :: */[
                        600,
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ], 0, (function (acc, n) {
                  return Prelude.JsPromise[/* sleepAndLog */1](n, "woke up after " + (String(n) + "")).then((function (param) {
                                return Promise.resolve(acc + n | 0);
                              }));
                })).then((function (total) {
                return Promise.resolve((console.log("Slept a total of " + (String(total) + " milliseconds.")), /* () */0));
              }));
}

function downloads(param) {
  return Prelude.JsPromise[/* reduce */2](/* :: */[
                "foo.com",
                /* :: */[
                  "bar.net",
                  /* :: */[
                    "baz.us",
                    /* :: */[
                      "cooldog.us",
                      /* [] */0
                    ]
                  ]
                ]
              ], /* () */0, (function (_acc, url) {
                  var url$1 = url;
                  return Prelude.JsPromise[/* sleepAndLog */1](888, "Downloaded " + (String(url$1) + ""));
                })).then((function (param) {
                return Promise.resolve((console.log("Downloads finished."), /* () */0));
              }));
}

downloads(/* () */0);

var P = 0;

exports.P = P;
exports.simple = simple;
exports.reduce = reduce;
exports.downloads = downloads;
/*  Not a pure module */
