// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Prelude = require("./helpers/Prelude.bs.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function rotations(lst) {
  var len = Belt_List.length(lst);
  var _acc = /* [] */0;
  var _i = 0;
  var lst$1 = lst;
  while(true) {
    var i = _i;
    var acc = _acc;
    if (i >= len) {
      return Belt_List.reverse(acc);
    } else {
      var match = Belt_Option.getWithDefault(Belt_List.splitAt(lst$1, i), /* tuple */[
            /* [] */0,
            /* [] */0
          ]);
      var acc$prime_000 = Belt_List.concat(match[1], match[0]);
      var acc$prime = /* :: */[
        acc$prime_000,
        acc
      ];
      _i = i + 1 | 0;
      _acc = acc$prime;
      continue ;
    }
  };
}

Prelude.Utils[/* logList */0](rotations(/* :: */[
          1,
          /* [] */0
        ]));

Prelude.Utils[/* logList */0](rotations(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* [] */0
            ]
          ]
        ]));

Prelude.Utils[/* logList */0](rotations(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ]
        ]));

exports.rotations = rotations;
/*  Not a pure module */
