// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Sqlite = require("./helpers/Sqlite.bs.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

var db = Sqlite.makeDatabase("test.db", undefined, undefined, undefined, 1000, /* () */0);

var createSql = "\n  DROP TABLE IF EXISTS players;\n\n  CREATE TABLE players (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    username VARCHAR(100),\n    level INTEGER\n  );\n";

db.exec(createSql);

var insert = db.prepare("INSERT INTO players VALUES ($id, $username, $level)");

function insertMany(rows) {
  return Belt_List.map(rows, (function (row) {
                return insert.run({
                            id: row[0],
                            username: row[1],
                            level: row[2]
                          });
              }));
}

console.log(insertMany(/* :: */[
          /* tuple */[
            1001,
            "Cowman",
            45
          ],
          /* :: */[
            /* tuple */[
              1002,
              "Batgirl",
              800
            ],
            /* :: */[
              /* tuple */[
                1003,
                "Manateewoman",
                9000
              ],
              /* [] */0
            ]
          ]
        ]));

console.log(db.prepare("SELECT SUM(level) as totalLevel FROM players").get());

db.close();

var result = /* () */0;

exports.db = db;
exports.createSql = createSql;
exports.insert = insert;
exports.insertMany = insertMany;
exports.result = result;
/* db Not a pure module */
