// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function traverse(_acc, _stack) {
  while(true) {
    var stack = _stack;
    var acc = _acc;
    if (stack) {
      var match = stack[0];
      if (match.tag) {
        var acc$prime_000 = match[0];
        var acc$prime = /* :: */[
          acc$prime_000,
          acc
        ];
        var stack$prime_000 = match[1];
        var stack$prime_001 = /* :: */[
          match[2],
          stack[1]
        ];
        var stack$prime = /* :: */[
          stack$prime_000,
          stack$prime_001
        ];
        _stack = stack$prime;
        _acc = acc$prime;
        continue ;
      } else {
        _stack = stack[1];
        _acc = /* :: */[
          match[0],
          acc
        ];
        continue ;
      }
    } else {
      return Belt_List.reverse(acc);
    }
  };
}

var myTree = /* Node */Block.__(1, [
    1,
    /* Node */Block.__(1, [
        2,
        /* Node */Block.__(1, [
            4,
            /* Leaf */Block.__(0, [41]),
            /* Leaf */Block.__(0, [42])
          ]),
        /* Node */Block.__(1, [
            6,
            /* Leaf */Block.__(0, [61]),
            /* Leaf */Block.__(0, [62])
          ])
      ]),
    /* Node */Block.__(1, [
        3,
        /* Node */Block.__(1, [
            5,
            /* Leaf */Block.__(0, [51]),
            /* Leaf */Block.__(0, [52])
          ]),
        /* Node */Block.__(1, [
            7,
            /* Leaf */Block.__(0, [71]),
            /* Leaf */Block.__(0, [72])
          ])
      ])
  ]);

console.log(Belt_List.toArray(traverse(/* [] */0, /* :: */[
              myTree,
              /* [] */0
            ])));

exports.traverse = traverse;
exports.myTree = myTree;
/*  Not a pure module */
