// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Zlib = require("zlib");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var str = Belt_Array.mapWithIndex(Belt_Array.make(100, "你好世界！"), (function (i, v) {
          var i$1 = i + 1 | 0;
          return "" + (String(i$1) + (". " + (String(v) + "\n")));
        })).join("");

var buffer = Buffer.from(str);

console.log("Original size:", String(buffer.length));

var buffer2 = Zlib.gzipSync(buffer);

console.log("Compressed size:", String(buffer2.length));

Fs.writeFileSync("output.gz", buffer2);

console.log("Wrote to file output.gz");

exports.str = str;
exports.buffer = buffer;
exports.buffer2 = buffer2;
/* str Not a pure module */
